/* !file overlay11 */
OpcodeCheck = 0x022DE714;
GetParameterCount = 0x022DE6CC;
ScriptEngineReturnTwo = 0x022E2DAC;
ScriptMenuRequestDefaultCase = 0x022E6A30;
ScriptMenuRequestFinalize = 0x022E71EC;
ScriptMenuUpdateDefaultCase = 0x022E7238;
ScriptMenuUpdateFinalize = 0x022E7798;
IS_BASE_GAME_MENU_FINISHED = 0x023257DC;

/* !file overlay29 */
ApplyMoveEffect = 0x0232F2A4;
ApplyMoveEffectHookAddr = 0x023302E4;
ApplyMoveEffectJumpAddr = 0x0233310C;
ApplyItemEffectHookAddr = 0x0231C438;
ApplyItemEffectJumpAddr = 0x0231D574;

/* Add your own symbols here... */

/* !file arm9 */
ShowKeyboardTypeCase3 = 0x02036C10;
ShowKeyboardTypeDefaultCase = 0x02036D3C;
ShowKeyboardReturn = 0x02036FA8;
PreprocessStringFromIdCallsite = 0x020396FC;
CHANGE_GIRATINA_FORM_HOOK = 0x2058958;
REVERT_GIRATINA_AND_SHAYMIN_FORM_HOOK = 0x20589F4;
CALC_DAMAGE_FORM_OFFENSE_HOOK = 0x230CAB4; 
CALC_DAMAGE_FORM_DEFENSE_HOOK = 0x230CBA8;
HOOK_DUNGEON_FORM_CHANGE = 0x2311B0C;
HOOK_DUNGEON_FORM_CHANGE_2 = 0x22FE160;
TRANSFORM_UNIT_HOOK = 0x2065930;
TRANSFORM_ADVENTURE_HOOK = 0x02065A1C;
TRANSFORM_MC1_HOOK = 0x2065B1C;
TRANSFORM_MC2_HOOK = 0x2065B2C;
TRANSFORM_MC3_HOOK = 0x2065B3C;
TRANSFORM_APPOINT_HOOK = 0x2065B4C;
TRANSFORM_HERO_HOOK = 0x2065B5C;
TRANSFORM_PARTNER_HOOK = 0x2065B6C;


/* ngl I don't remember which file these are from. Or if I use all of them. - Lappy */
UnknownFunction1 = 0x234BE94;
UnknownFunction2 = 0x230525C;
TransformationVFX = 0x22E6FA4;
UnknownFunction3 = 0x22FA8AC;
GetAppointedMemberIdx = 0x2056C20;